"""Record installed dependency versions without editable paths or credentials.

Run with the verified project virtual environment after an intentional dependency
update. Both locks include Windows/POSIX marker branches; exact-version replay
should be revalidated on supported Python and container platforms.
"""

from importlib.metadata import distribution, distributions
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]


def runtime_packages() -> set[str]:
    """Traverse mandatory metadata requirements including explicitly requested extras."""
    selected: set[str] = set()
    pending = [(Requirement(item), {""}) for item in distribution("parallax-risk").requires or []]
    while pending:
        requirement, parent_extras = pending.pop()
        if requirement.marker and not any(
            requirement.marker.evaluate({"extra": extra}) for extra in parent_extras
        ):
            continue
        name = canonicalize_name(requirement.name)
        if name in selected:
            continue
        selected.add(name)
        package = distribution(requirement.name)
        extras = {"", *requirement.extras}
        pending.extend((Requirement(item), extras) for item in package.requires or [])
    return selected


def main() -> None:
    """Write reproducibility snapshots from the current installed environment."""
    installed = {
        canonicalize_name(package.metadata["Name"]): package.version
        for package in distributions()
        if canonicalize_name(package.metadata["Name"]) not in {"parallax-risk", "pip"}
    }
    # Keep runtime dependencies present across platform-specific metadata branches.
    runtime = runtime_packages() | {"tzdata", "greenlet", "colorama"}
    header = "# Generated by scripts/lock_dependencies.py; no local paths or secrets.\n"
    for path, names in (
        ("requirements-runtime.lock", runtime),
        ("requirements-dev.lock", set(installed)),
    ):
        lines = [f"{name}=={installed[name]}" for name in sorted(names)]
        (ROOT / path).write_text(header + "\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
