"""Record installed dependency versions without editable paths or credentials.

Run with the verified project virtual environment after an intentional dependency
update. Both locks include Windows/POSIX marker branches; exact-version replay
should be revalidated on supported Python and container platforms.
"""

from importlib.metadata import distribution, distributions
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
PLATFORM_DEV_MARKERS = {
    "appnope": "platform_system == 'Darwin'",
    "pexpect": "sys_platform != 'win32' and sys_platform != 'emscripten'",
    "ptyprocess": "sys_platform != 'win32' and sys_platform != 'emscripten'",
}


def runtime_packages() -> set[str]:
    """Traverse mandatory metadata requirements including explicitly requested extras."""
    selected: set[str] = set()
    pending = [(Requirement(item), {""}) for item in distribution("parallax-risk").requires or []]
    while pending:
        requirement, parent_extras = pending.pop()
        if requirement.marker and not any(
            requirement.marker.evaluate({"extra": extra}) for extra in parent_extras
        ):
            continue
        name = canonicalize_name(requirement.name)
        if name in selected:
            continue
        selected.add(name)
        package = distribution(requirement.name)
        extras = {"", *requirement.extras}
        pending.extend((Requirement(item), extras) for item in package.requires or [])
    return selected


def main() -> None:
    """Write reproducibility snapshots from the current installed environment."""
    installed = {
        canonicalize_name(package.metadata["Name"]): package.version
        for package in distributions()
        if canonicalize_name(package.metadata["Name"]) not in {"parallax-risk", "pip"}
    }
    # Preserve inactive-platform pins when regenerating from a locked Windows environment.
    previous_lock = ROOT / "requirements-dev.lock"
    if previous_lock.exists():
        for line in previous_lock.read_text(encoding="utf-8").splitlines():
            if not line or line.startswith("#"):
                continue
            previous = Requirement(line)
            name = canonicalize_name(previous.name)
            if name in PLATFORM_DEV_MARKERS and name not in installed:
                (pin,) = previous.specifier
                if pin.operator != "==":
                    raise ValueError("Cross-platform dependency pins must use exact versions")
                installed[name] = pin.version
    # Keep runtime dependencies present across platform-specific metadata branches.
    runtime = runtime_packages() | {"tzdata", "greenlet", "colorama"}
    header = "# Generated by scripts/lock_dependencies.py; no local paths or secrets.\n"
    for path, names in (
        ("requirements-runtime.lock", runtime),
        ("requirements-dev.lock", set(installed)),
    ):
        lines = [
            f"{name}=={installed[name]}"
            + (f"; {PLATFORM_DEV_MARKERS[name]}" if name in PLATFORM_DEV_MARKERS else "")
            for name in sorted(names)
        ]
        (ROOT / path).write_text(header + "\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
